{
  // gROOT->ProcessLine(".include /net/hisrv0001/home/dav2105/include");
  // gStyle->SetPalette(1,0);
  // gROOT->ProcessLine("#include <vector>");
  // gStyle->SetPadColor(0);
  // gStyle->SetPadBorderSize(0);
  // gStyle->SetPadBorderMode(0);
  // gStyle->SetCanvasColor(0);
  // gStyle->SetCanvasBorderMode(0);
  // gStyle->SetCanvasBorderSize(0);
  // gStyle->SetFrameBorderMode(0);
  // gStyle->SetFrameLineColor(0);
  // gStyle->SetTitleColor(0);
  // gStyle->SetTitleBorderSize(0);
  // gStyle->SetPalette(1,0);
  // gStyle->SetPadTickX(1);
  // gStyle->SetPadTickY(1);
  // gStyle->SetPadColor(0);
  // gStyle->SetPadBorderSize(0);
  // gStyle->SetPadBorderMode(0);
  // gStyle->SetCanvasColor(0);
  // gStyle->SetCanvasBorderMode(0);
  // gStyle->SetCanvasBorderSize(0);
  // gStyle->SetFrameBorderMode(0);
  // gStyle->SetFrameLineColor(0);
  // gStyle->SetFrameFillColor(0);
  // gStyle->SetTextFont(62);
  // gStyle->SetLabelFont(42,"XYZ");
  // gStyle->SetTitleFont(42,"XYZ");
  // gStyle->SetTitleColor(0);
  // gStyle->SetTitleBorderSize(0);
  // gStyle->SetTitleXSize(.055);
  // gStyle->SetTitleYSize(.055);
  // gStyle->SetTitleXOffset(1.0);
  // gStyle->SetTitleYOffset(1.2);
  // gStyle->SetLabelSize(0.045,"XYZ");
  // gStyle->SetLabelOffset(0.01,"X");
  // gStyle->SetLabelOffset(0.01,"Y");
  // gStyle->SetTitleColor(1,"XYZ");
     // gStyle->SetHistFillColor(1);
      // gStyle->SetHistFillStyle(0);
  // gStyle->SetHistLineColor(1);
  // gStyle->SetHistLineStyle(0);
  // gStyle->SetHistLineWidth(3);
  // gStyle->SetHistLineWidth(1);
  // gStyle->SetEndErrorSize(0);
       // gStyle->SetErrorX(0);
  // gStyle->SetMarkerStyle(20);
  // gStyle->SetMarkerSize(1);
  // gStyle->SetStatColor(0);
  // gStyle->SetStatBorderSize(1);
  // gStyle->SetOptStat(1);
  // gStyle->SetPadLeftMargin(0.18);
  // gStyle->SetPadBottomMargin(0.15);
  // gStyle->SetPadTopMargin(0.05);
            // gStyle->SetPadRightMargin(0.14);
  // gStyle->SetPadRightMargin(0.05);
  // gStyle->SetStats(1);
  // gStyle->SetOptFit(1111);
  //AutoLibraryLoader::enable();

  // gSystem->Load( "libFWCoreFWLite" );
  // gSystem->Load("libDataFormatsFWLite");
  // gSystem->Load("libDataFormatsFWLite.so");
  // gSystem->Load("libDataFormatsPatCandidates.so");
  
  // gInterpreter->ExecuteMacro("~davidlw/useful_macros/MITStyle.C");
  gInterpreter->ExecuteMacro("/home/ursu/MITStyle.C");
  // return;
  gROOT->ForceStyle();
}
